Update 05-submission.md to add missing command (#376)
* Update 05-submission.md to add missing command

This fixes a problem with the instructions.

If you follow them as stated (as I did), when you go to build the manifest, you will get an error:

    error: No remote refs found for ‘flathub’
    Error installing deps: running `flatpak --user install -y --noninteractive flathub org.kde.Sdk/x86_64/5.15-23.08`: Child process exited with code 1

The repo already was added system wide, and adding it again did not change the error.

Adding the repo with the --user flag allowed the build command to continue.

* Update docs/02-for-app-authors/05-submission.md

Co-authored-by: bbhtt <bbhtt.zn0i8@slmail.me>

---------

Co-authored-by: bbhtt <bbhtt.zn0i8@slmail.me>